### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by xSirLalo** [m1ge0/bootsjet#2]
It seems to have a problem with the clear theme, it does not load the styles correctly.

LARAVEL 10.33.0
VITE v4.5.0
PHP 8.2.8

![image](https://github.com/m1ge0/bootsjet/assets/32373378/279db407-7839-4909-ba68-0de411ff100d)

![image](https://github.com/m1ge0/bootsjet/assets/32373378/e8644d94-d029-4da1-abd0-39d4a054aecc)

**Comment by m1ge0** [comment]
Hey, 
could you please provide more details of your .scss file? 
And do you mean the light mode with the clear theme?

**Comment by m1ge0** [comment]
I think I now where I have forgotten something. It's the auto theme, which causes this little bug. For now, u can add 

`.card {
  background-color: #fff !important;
}

input {
  background-color: #fff !important;
}`

to your custom.scss. 
Then it should be fixed...

**Comment by xSirLalo** [comment]
If I comment out the custom app.scss file, it seems to work correctly, but I still see grayed out inputs and cards.

![image](https://github.com/m1ge0/bootsjet/assets/32373378/600828f5-e57b-4361-bede-07b42b11dc1e)


![image](https://github.com/m1ge0/bootsjet/assets/32373378/55093e63-06a7-40f9-a790-c4aabb468789)


![image](https://github.com/m1ge0/bootsjet/assets/32373378/23b572a5-9fd7-475f-9b40-91c1db467d7e)
